/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * Unknown integration
 */
export type Response404Data = {
    message?: string | undefined;
};

/**
 * Unknown integration
 */
export class Response404 extends Error {
    /** The original data that was passed to this error instance. */
    data$: Response404Data;

    constructor(err: Response404Data) {
        super("");
        this.data$ = err;

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "Response404";
    }
}

/** @internal */
export namespace Response404$ {
    export type Inbound = {
        message?: string | undefined;
    };

    export const inboundSchema: z.ZodType<Response404, z.ZodTypeDef, Inbound> = z
        .object({
            message: z.string().optional(),
        })
        .transform((v) => {
            return new Response404({
                ...(v.message === undefined ? null : { message: v.message }),
            });
        });
    export type Outbound = {
        message?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Response404> = z
        .instanceof(Response404)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    message: z.string().optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.message === undefined ? null : { message: v.message }),
                    };
                })
        );
}
