workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/nango/nango/my-source
targets:
    nango-ts:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $NPM_TOKEN
