workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: ./openapi_improved.yaml
        registry:
            location: registry.speakeasyapi.dev/nango/nango/my-source
targets:
    nango-ts:
        target: typescript
        source: my-source
