/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type CreateMetadataRequestBody = {};

export type CreateMetadataRequest = {
    /**
     * The connection ID used to create the connection.
     */
    connectionId: string;
    /**
     * The integration ID used to create the connection (aka Unique Key).
     */
    providerConfigKey: string;
    requestBody: CreateMetadataRequestBody;
};

export type CreateMetadataResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreateMetadataRequestBody$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<CreateMetadataRequestBody, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateMetadataRequestBody> =
        z.object({});
}

/** @internal */
export namespace CreateMetadataRequest$ {
    export type Inbound = {
        connectionId: string;
        "Provider-Config-Key": string;
        RequestBody: CreateMetadataRequestBody$.Inbound;
    };

    export const inboundSchema: z.ZodType<CreateMetadataRequest, z.ZodTypeDef, Inbound> = z
        .object({
            connectionId: z.string(),
            "Provider-Config-Key": z.string(),
            RequestBody: z.lazy(() => CreateMetadataRequestBody$.inboundSchema),
        })
        .transform((v) => {
            return {
                connectionId: v.connectionId,
                providerConfigKey: v["Provider-Config-Key"],
                requestBody: v.RequestBody,
            };
        });

    export type Outbound = {
        connectionId: string;
        "Provider-Config-Key": string;
        RequestBody: CreateMetadataRequestBody$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateMetadataRequest> = z
        .object({
            connectionId: z.string(),
            providerConfigKey: z.string(),
            requestBody: z.lazy(() => CreateMetadataRequestBody$.outboundSchema),
        })
        .transform((v) => {
            return {
                connectionId: v.connectionId,
                "Provider-Config-Key": v.providerConfigKey,
                RequestBody: v.requestBody,
            };
        });
}

/** @internal */
export namespace CreateMetadataResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<CreateMetadataResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateMetadataResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
