/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type CreateActionTriggerRequest = {
    /**
     * The connection ID used to create the connection.
     */
    connectionId: string;
    /**
     * The integration ID used to create the connection (aka Unique Key).
     */
    providerConfigKey: string;
    createActionTriggerRequest: components.CreateActionTriggerRequest;
};

export type CreateActionTriggerResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Returns the result of the action
     */
    createActionTriggerResponse?: components.CreateActionTriggerResponse | undefined;
};

/** @internal */
export namespace CreateActionTriggerRequest$ {
    export const inboundSchema: z.ZodType<CreateActionTriggerRequest, z.ZodTypeDef, unknown> = z
        .object({
            "Connection-Id": z.string(),
            "Provider-Config-Key": z.string(),
            CreateActionTriggerRequest: components.CreateActionTriggerRequest$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "Connection-Id": "connectionId",
                "Provider-Config-Key": "providerConfigKey",
                CreateActionTriggerRequest: "createActionTriggerRequest",
            });
        });

    export type Outbound = {
        "Connection-Id": string;
        "Provider-Config-Key": string;
        CreateActionTriggerRequest: components.CreateActionTriggerRequest$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateActionTriggerRequest> = z
        .object({
            connectionId: z.string(),
            providerConfigKey: z.string(),
            createActionTriggerRequest: components.CreateActionTriggerRequest$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                connectionId: "Connection-Id",
                providerConfigKey: "Provider-Config-Key",
                createActionTriggerRequest: "CreateActionTriggerRequest",
            });
        });
}

/** @internal */
export namespace CreateActionTriggerResponse$ {
    export const inboundSchema: z.ZodType<CreateActionTriggerResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            CreateActionTriggerResponse:
                components.CreateActionTriggerResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
                CreateActionTriggerResponse: "createActionTriggerResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        CreateActionTriggerResponse?: components.CreateActionTriggerResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateActionTriggerResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            createActionTriggerResponse:
                components.CreateActionTriggerResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
                createActionTriggerResponse: "CreateActionTriggerResponse",
            });
        });
}
