/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

export type DeleteConnectionsRequest = {
    /**
     * The connection ID used to create the connection.
     */
    connectionId: string;
    /**
     * The integration ID used to create the connection (aka Unique Key).
     */
    providerConfigKey: string;
};

export type DeleteConnectionsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeleteConnectionsRequest$ {
    export const inboundSchema: z.ZodType<DeleteConnectionsRequest, z.ZodTypeDef, unknown> = z
        .object({
            connectionId: z.string(),
            provider_config_key: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                provider_config_key: "providerConfigKey",
            });
        });

    export type Outbound = {
        connectionId: string;
        provider_config_key: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteConnectionsRequest> = z
        .object({
            connectionId: z.string(),
            providerConfigKey: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                providerConfigKey: "provider_config_key",
            });
        });
}

/** @internal */
export namespace DeleteConnectionsResponse$ {
    export const inboundSchema: z.ZodType<DeleteConnectionsResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteConnectionsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
