/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type DeleteConnectionsRequest = {
    /**
     * The connection ID used to create the connection.
     */
    connectionId: string;
    /**
     * The integration ID used to create the connection (aka Unique Key).
     */
    providerConfigKey: string;
};

export type DeleteConnectionsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeleteConnectionsRequest$ {
    export type Inbound = {
        connectionId: string;
        provider_config_key: string;
    };

    export const inboundSchema: z.ZodType<DeleteConnectionsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            connectionId: z.string(),
            provider_config_key: z.string(),
        })
        .transform((v) => {
            return {
                connectionId: v.connectionId,
                providerConfigKey: v.provider_config_key,
            };
        });

    export type Outbound = {
        connectionId: string;
        provider_config_key: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteConnectionsRequest> = z
        .object({
            connectionId: z.string(),
            providerConfigKey: z.string(),
        })
        .transform((v) => {
            return {
                connectionId: v.connectionId,
                provider_config_key: v.providerConfigKey,
            };
        });
}

/** @internal */
export namespace DeleteConnectionsResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<DeleteConnectionsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteConnectionsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
