/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetEnvironmentVariableResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Retrieve the environment variables as added in the Nango dashboard
     */
    getEnvironmentVariableResponse?: Array<components.GetEnvironmentVariableResponse> | undefined;
};

/** @internal */
export namespace GetEnvironmentVariableResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        GetEnvironmentVariableResponse?:
            | Array<components.GetEnvironmentVariableResponse$.Inbound>
            | undefined;
    };

    export const inboundSchema: z.ZodType<GetEnvironmentVariableResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            GetEnvironmentVariableResponse: z
                .array(components.GetEnvironmentVariableResponse$.inboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.GetEnvironmentVariableResponse === undefined
                    ? null
                    : { getEnvironmentVariableResponse: v.GetEnvironmentVariableResponse }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        GetEnvironmentVariableResponse?:
            | Array<components.GetEnvironmentVariableResponse$.Outbound>
            | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetEnvironmentVariableResponse> =
        z
            .object({
                contentType: z.string(),
                statusCode: z.number().int(),
                rawResponse: z.instanceof(Response).transform(() => {
                    throw new Error("Response cannot be serialized");
                }),
                getEnvironmentVariableResponse: z
                    .array(components.GetEnvironmentVariableResponse$.outboundSchema)
                    .optional(),
            })
            .transform((v) => {
                return {
                    ContentType: v.contentType,
                    StatusCode: v.statusCode,
                    RawResponse: v.rawResponse,
                    ...(v.getEnvironmentVariableResponse === undefined
                        ? null
                        : { GetEnvironmentVariableResponse: v.getEnvironmentVariableResponse }),
                };
            });
}
