/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./createactiontrigger";
export * from "./createconnection";
export * from "./createintegrations";
export * from "./createmetadata";
export * from "./createproxy";
export * from "./createsyncpause";
export * from "./createsyncstart";
export * from "./createsynctrigger";
export * from "./deleteconnections";
export * from "./deleteintegration";
export * from "./deleteproxy";
export * from "./getconnections";
export * from "./getenvironmentvariable";
export * from "./getintegration";
export * from "./getproxy";
export * from "./getrecord";
export * from "./getsyncrecord";
export * from "./getsyncstatus";
export * from "./listconnections";
export * from "./listintegrations";
export * from "./patchproxy";
export * from "./putproxy";
export * from "./updateconnectionfrequency";
export * from "./updateintegration";
export * from "./updatemetadata";
