/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ListConnectionsRequest = {
    /**
     * Filter the list of connections based on this connection ID.
     */
    connectionId?: string | undefined;
};

/** @internal */
export namespace ListConnectionsRequest$ {
    export const inboundSchema: z.ZodType<ListConnectionsRequest, z.ZodTypeDef, unknown> = z.object(
        {
            connectionId: z.string().optional(),
        }
    );

    export type Outbound = {
        connectionId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListConnectionsRequest> =
        z.object({
            connectionId: z.string().optional(),
        });
}
