/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type ListConnectionsRequest = {
    /**
     * Filter the list of connections based on this connection ID.
     */
    connectionId?: string | undefined;
};

export type ListConnectionsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successfully returned a list of connections
     */
    getConnectionResponse?: components.GetConnectionResponse | undefined;
};

/** @internal */
export namespace ListConnectionsRequest$ {
    export type Inbound = {
        connectionId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ListConnectionsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            connectionId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.connectionId === undefined ? null : { connectionId: v.connectionId }),
            };
        });

    export type Outbound = {
        connectionId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListConnectionsRequest> = z
        .object({
            connectionId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.connectionId === undefined ? null : { connectionId: v.connectionId }),
            };
        });
}

/** @internal */
export namespace ListConnectionsResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        GetConnectionResponse?: components.GetConnectionResponse$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<ListConnectionsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            GetConnectionResponse: components.GetConnectionResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.GetConnectionResponse === undefined
                    ? null
                    : { getConnectionResponse: v.GetConnectionResponse }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        GetConnectionResponse?: components.GetConnectionResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListConnectionsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            getConnectionResponse: components.GetConnectionResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.getConnectionResponse === undefined
                    ? null
                    : { GetConnectionResponse: v.getConnectionResponse }),
            };
        });
}
