/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type UpdateConnectionFrequencyResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successfully updated the frequency
     */
    updateConnectionFrequencyResponse?: components.UpdateConnectionFrequencyResponse | undefined;
};

/** @internal */
export namespace UpdateConnectionFrequencyResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        UpdateConnectionFrequencyResponse?:
            | components.UpdateConnectionFrequencyResponse$.Inbound
            | undefined;
    };

    export const inboundSchema: z.ZodType<
        UpdateConnectionFrequencyResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            UpdateConnectionFrequencyResponse:
                components.UpdateConnectionFrequencyResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.UpdateConnectionFrequencyResponse === undefined
                    ? null
                    : { updateConnectionFrequencyResponse: v.UpdateConnectionFrequencyResponse }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        UpdateConnectionFrequencyResponse?:
            | components.UpdateConnectionFrequencyResponse$.Outbound
            | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UpdateConnectionFrequencyResponse
    > = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            updateConnectionFrequencyResponse:
                components.UpdateConnectionFrequencyResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.updateConnectionFrequencyResponse === undefined
                    ? null
                    : { UpdateConnectionFrequencyResponse: v.updateConnectionFrequencyResponse }),
            };
        });
}
