/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

export type UpdateMetadataRequestBody = {};

export type UpdateMetadataRequest = {
    /**
     * The connection ID used to create the connection.
     */
    connectionId: string;
    /**
     * The integration ID used to create the connection (aka Unique Key).
     */
    providerConfigKey: string;
    requestBody: UpdateMetadataRequestBody;
};

/**
 * Successfully updated the metadata
 */
export type UpdateMetadataResponseBody = {};

export type UpdateMetadataResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successfully updated the metadata
     */
    object?: UpdateMetadataResponseBody | undefined;
};

/** @internal */
export namespace UpdateMetadataRequestBody$ {
    export const inboundSchema: z.ZodType<UpdateMetadataRequestBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateMetadataRequestBody> =
        z.object({});
}

/** @internal */
export namespace UpdateMetadataRequest$ {
    export const inboundSchema: z.ZodType<UpdateMetadataRequest, z.ZodTypeDef, unknown> = z
        .object({
            connectionId: z.string(),
            "Provider-Config-Key": z.string(),
            RequestBody: z.lazy(() => UpdateMetadataRequestBody$.inboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                "Provider-Config-Key": "providerConfigKey",
                RequestBody: "requestBody",
            });
        });

    export type Outbound = {
        connectionId: string;
        "Provider-Config-Key": string;
        RequestBody: UpdateMetadataRequestBody$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateMetadataRequest> = z
        .object({
            connectionId: z.string(),
            providerConfigKey: z.string(),
            requestBody: z.lazy(() => UpdateMetadataRequestBody$.outboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                providerConfigKey: "Provider-Config-Key",
                requestBody: "RequestBody",
            });
        });
}

/** @internal */
export namespace UpdateMetadataResponseBody$ {
    export const inboundSchema: z.ZodType<UpdateMetadataResponseBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateMetadataResponseBody> =
        z.object({});
}

/** @internal */
export namespace UpdateMetadataResponse$ {
    export const inboundSchema: z.ZodType<UpdateMetadataResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => UpdateMetadataResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: UpdateMetadataResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateMetadataResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => UpdateMetadataResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
