/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

export type CreateActionTriggerResponse = {
    /**
     * The data returned by the action
     */
    yourProperties?: string | undefined;
};

/** @internal */
export namespace CreateActionTriggerResponse$ {
    export const inboundSchema: z.ZodType<CreateActionTriggerResponse, z.ZodTypeDef, unknown> = z
        .object({
            "your-properties": z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "your-properties": "yourProperties",
            });
        });

    export type Outbound = {
        "your-properties"?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateActionTriggerResponse> = z
        .object({
            yourProperties: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                yourProperties: "your-properties",
            });
        });
}
