/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * The necessary input for your action's 'runAction' function.
 */
export type Input = {};

export type CreateActionTriggerRequest = {
    /**
     * The name of the action to trigger.
     */
    actionName: string;
    /**
     * The necessary input for your action's 'runAction' function.
     */
    input?: Input | undefined;
};

/** @internal */
export namespace Input$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<Input, z.ZodTypeDef, Inbound> = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Input> = z.object({});
}

/** @internal */
export namespace CreateActionTriggerRequest$ {
    export type Inbound = {
        action_name: string;
        input?: Input$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateActionTriggerRequest, z.ZodTypeDef, Inbound> = z
        .object({
            action_name: z.string(),
            input: z.lazy(() => Input$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                actionName: v.action_name,
                ...(v.input === undefined ? null : { input: v.input }),
            };
        });

    export type Outbound = {
        action_name: string;
        input?: Input$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateActionTriggerRequest> = z
        .object({
            actionName: z.string(),
            input: z.lazy(() => Input$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                action_name: v.actionName,
                ...(v.input === undefined ? null : { input: v.input }),
            };
        });
}
