/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateConnectionRequest = {};

/** @internal */
export namespace CreateConnectionRequest$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<CreateConnectionRequest, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateConnectionRequest> =
        z.object({});
}
