/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The last action seen on this record
 */
export enum LastAction {
    Added = "ADDED",
    Updated = "UPDATED",
    Deleted = "DELETED",
}

export type NangoMetadata = {
    /**
     * The timestamp at which Nango detected the record as deleted
     */
    deletedAt?: string | undefined;
    /**
     * The last action seen on this record
     */
    lastAction?: LastAction | undefined;
    /**
     * The timestamp at which Nango first saw this record
     */
    firstSeenAt?: string | undefined;
    /**
     * The timestamp at which Nango last detected a change to this record
     */
    lastModifiedAt?: string | undefined;
};

export type GetSyncRecordResponse = {
    /**
     * The data Nango synced in for you
     */
    yourProperties?: string | undefined;
    nangoMetadata?: NangoMetadata | undefined;
};

/** @internal */
export const LastAction$ = z.nativeEnum(LastAction);

/** @internal */
export namespace NangoMetadata$ {
    export type Inbound = {
        deleted_at?: string | undefined;
        last_action?: LastAction | undefined;
        first_seen_at?: string | undefined;
        last_modified_at?: string | undefined;
    };

    export const inboundSchema: z.ZodType<NangoMetadata, z.ZodTypeDef, Inbound> = z
        .object({
            deleted_at: z.string().optional(),
            last_action: LastAction$.optional(),
            first_seen_at: z.string().optional(),
            last_modified_at: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.deleted_at === undefined ? null : { deletedAt: v.deleted_at }),
                ...(v.last_action === undefined ? null : { lastAction: v.last_action }),
                ...(v.first_seen_at === undefined ? null : { firstSeenAt: v.first_seen_at }),
                ...(v.last_modified_at === undefined
                    ? null
                    : { lastModifiedAt: v.last_modified_at }),
            };
        });

    export type Outbound = {
        deleted_at?: string | undefined;
        last_action?: LastAction | undefined;
        first_seen_at?: string | undefined;
        last_modified_at?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, NangoMetadata> = z
        .object({
            deletedAt: z.string().optional(),
            lastAction: LastAction$.optional(),
            firstSeenAt: z.string().optional(),
            lastModifiedAt: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.deletedAt === undefined ? null : { deleted_at: v.deletedAt }),
                ...(v.lastAction === undefined ? null : { last_action: v.lastAction }),
                ...(v.firstSeenAt === undefined ? null : { first_seen_at: v.firstSeenAt }),
                ...(v.lastModifiedAt === undefined ? null : { last_modified_at: v.lastModifiedAt }),
            };
        });
}

/** @internal */
export namespace GetSyncRecordResponse$ {
    export type Inbound = {
        "your-properties"?: string | undefined;
        _nango_metadata?: NangoMetadata$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetSyncRecordResponse, z.ZodTypeDef, Inbound> = z
        .object({
            "your-properties": z.string().optional(),
            _nango_metadata: z.lazy(() => NangoMetadata$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v["your-properties"] === undefined
                    ? null
                    : { yourProperties: v["your-properties"] }),
                ...(v._nango_metadata === undefined ? null : { nangoMetadata: v._nango_metadata }),
            };
        });

    export type Outbound = {
        "your-properties"?: string | undefined;
        _nango_metadata?: NangoMetadata$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetSyncRecordResponse> = z
        .object({
            yourProperties: z.string().optional(),
            nangoMetadata: z.lazy(() => NangoMetadata$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.yourProperties === undefined
                    ? null
                    : { "your-properties": v.yourProperties }),
                ...(v.nangoMetadata === undefined ? null : { _nango_metadata: v.nangoMetadata }),
            };
        });
}
