/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type PutProxyRequest = {
    dollarANYBODYPARAMS?: string | undefined;
};

/** @internal */
export namespace PutProxyRequest$ {
    export type Inbound = {
        $ANY_BODY_PARAMS?: string | undefined;
    };

    export const inboundSchema: z.ZodType<PutProxyRequest, z.ZodTypeDef, Inbound> = z
        .object({
            $ANY_BODY_PARAMS: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.$ANY_BODY_PARAMS === undefined
                    ? null
                    : { dollarANYBODYPARAMS: v.$ANY_BODY_PARAMS }),
            };
        });

    export type Outbound = {
        $ANY_BODY_PARAMS?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutProxyRequest> = z
        .object({
            dollarANYBODYPARAMS: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.dollarANYBODYPARAMS === undefined
                    ? null
                    : { $ANY_BODY_PARAMS: v.dollarANYBODYPARAMS }),
            };
        });
}
