/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateConnectionFrequencyResponse = {
    /**
     * The updated frequency value
     */
    frequency?: string | undefined;
};

/** @internal */
export namespace UpdateConnectionFrequencyResponse$ {
    export const inboundSchema: z.ZodType<
        UpdateConnectionFrequencyResponse,
        z.ZodTypeDef,
        unknown
    > = z.object({
        frequency: z.string().optional(),
    });

    export type Outbound = {
        frequency?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UpdateConnectionFrequencyResponse
    > = z.object({
        frequency: z.string().optional(),
    });
}
